spring.application.name=user-service


server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/tradenestdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kolkata

spring.datasource.username=root
spring.datasource.password=sql123@18pj

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


logging.level.org.hibernate.SQL=DEBUG

logging.level.org.hibernate.orm.jdbc.bind=TRACE

spring.jackson.serialization.fail-on-empty-beans=false


# =========================
# JWT Configuration
# =========================

jwt.secret=VGhpcy1Jcy1BLVZlcnktU2VjdXJlLUtleS1Gb3ItVHJhZGVOZXN0LVNwcmluZy1Cb290LUFwcA==
jwt.expiration=86400000